image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  IMAGE_REPOSITORY: crinis/typo3-php

before_script:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD https://index.docker.io/v1/

build-5.6-apache:
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:5.6-apache -f 5.6/apache/Dockerfile 5.6/apache/
    - docker push $IMAGE_REPOSITORY:5.6-apache
    - docker tag $IMAGE_REPOSITORY:5.6-apache $IMAGE_REPOSITORY:5.6
    - docker push $IMAGE_REPOSITORY:5.6

build-5.6-apache:on-tags:
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php5.6-apache -f 5.6/apache/Dockerfile 5.6/apache/
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php5.6-apache
    - docker tag $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php5.6-apache $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php5.6
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php5.6

build-5.6-fpm-alpine:
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:5.6-fpm-alpine -f 5.6/fpm-alpine/Dockerfile 5.6/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:5.6-fpm-alpine

build-5.6-fpm-alpine:on-tags:
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php5.6-fpm-alpine -f 5.6/fpm-alpine/Dockerfile 5.6/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php5.6-fpm-alpine

build-7.1-apache:
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.1-apache -f 7.1/apache/Dockerfile 7.1/apache/
    - docker push $IMAGE_REPOSITORY:7.1-apache
    - docker tag $IMAGE_REPOSITORY:7.1-apache $IMAGE_REPOSITORY:7.1
    - docker push $IMAGE_REPOSITORY:7.1

build-7.1-apache:on-tags:
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.1-apache -f 7.1/apache/Dockerfile 7.1/apache/
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.1-apache
    - docker tag $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.1-apache $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.1
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.1

build-7.1-fpm-alpine:
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.1-fpm-alpine -f 7.1/fpm-alpine/Dockerfile 7.1/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:7.1-fpm-alpine

build-7.1-fpm-alpine:on-tags:
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.1-fpm-alpine -f 7.1/fpm-alpine/Dockerfile 7.1/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.1-fpm-alpine

build-7.2-apache:
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.2-apache -f 7.2/apache/Dockerfile 7.2/apache/
    - docker push $IMAGE_REPOSITORY:7.2-apache
    - docker tag $IMAGE_REPOSITORY:7.2-apache $IMAGE_REPOSITORY:7.2
    - docker push $IMAGE_REPOSITORY:7.2
    - docker tag $IMAGE_REPOSITORY:7.2-apache $IMAGE_REPOSITORY:latest
    - docker push $IMAGE_REPOSITORY:latest

build-7.2-apache:on-tags:
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.2-apache -f 7.2/apache/Dockerfile 7.2/apache/
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.2-apache
    - docker tag $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.2-apache $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.2
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.2
    - docker tag $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.2-apache $IMAGE_REPOSITORY:$CI_COMMIT_TAG
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG

build-7.2-fpm-alpine:
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.2-fpm-alpine -f 7.2/fpm-alpine/Dockerfile 7.2/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:7.2-fpm-alpine

build-7.2-fpm-alpine:on-tags:
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.2-fpm-alpine -f 7.2/fpm-alpine/Dockerfile 7.2/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG-php7.2-fpm-alpine

build:on-schedules:
  only:
    - schedules
  variables:
    MIN_VERSION: 0.1.1
  script:
    - apk update && apk add git sort
    - function version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }
    - > 
      for git_tag in $(git tag); do
        if version_gt $git_tag '0.1.1'; then
          git checkout tags/$git_tag
          docker build -t $IMAGE_REPOSITORY:$git_tag-php5.6-apache -f 5.6/apache/Dockerfile 5.6/apache/
          docker push $IMAGE_REPOSITORY:$git_tag-php5.6-apache
          docker tag $IMAGE_REPOSITORY:$git_tag-php5.6-apache $IMAGE_REPOSITORY:$git_tag-php5.6
          docker push $IMAGE_REPOSITORY:$git_tag-php5.6
          docker build -t $IMAGE_REPOSITORY:$git_tag-php5.6-fpm-alpine -f 5.6/fpm-alpine/Dockerfile 5.6/fpm-alpine/
          docker push $IMAGE_REPOSITORY:$git_tag-php5.6-fpm-alpine
          docker build -t $IMAGE_REPOSITORY:$git_tag-php7.1-apache -f 7.1/apache/Dockerfile 7.1/apache/
          docker push $IMAGE_REPOSITORY:$git_tag-php7.1-apache
          docker tag $IMAGE_REPOSITORY:$git_tag-php7.1-apache $IMAGE_REPOSITORY:$git_tag-php7.1
          docker push $IMAGE_REPOSITORY:$git_tag-php7.1
          docker build -t $IMAGE_REPOSITORY:$git_tag-php7.1-fpm-alpine -f 7.1/fpm-alpine/Dockerfile 7.1/fpm-alpine/
          docker push $IMAGE_REPOSITORY:$git_tag-php7.1-fpm-alpine
          docker build -t $IMAGE_REPOSITORY:$git_tag-php7.2-apache -f 7.2/apache/Dockerfile 7.2/apache/
          docker push $IMAGE_REPOSITORY:$git_tag-php7.2-apache
          docker tag $IMAGE_REPOSITORY:$git_tag-php7.2-apache $IMAGE_REPOSITORY:$git_tag-php7.2
          docker push $IMAGE_REPOSITORY:$git_tag-php7.2
          docker tag $IMAGE_REPOSITORY:$git_tag-php7.2-apache $IMAGE_REPOSITORY:$git_tag
          docker push $IMAGE_REPOSITORY:$git_tag
        fi
      done

after_script:
  - docker logout
