image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  IMAGE_REPOSITORY: crinis/typo3-php

before_script:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD https://index.docker.io/v1/

stages:
  - build
  - trigger-typo3-build

build-5.6-apache:
  stage: build
  except:
    - schedules
  script:
    - docker build -t ${IMAGE_REPOSITORY}:5.6-apache -f 5.6/apache/Dockerfile 5.6/apache/
    - docker push $IMAGE_REPOSITORY:5.6-apache

build-5.6-apache-stretch:on-tags:
  stage: build
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:5.6-apache-$CI_COMMIT_TAG -f 5.6/apache/Dockerfile 5.6/apache/
    - docker push $IMAGE_REPOSITORY:5.6-apache-$CI_COMMIT_TAG

build-5.6-fpm-alpine:
  stage: build
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:5.6-fpm-alpine -f 5.6/fpm-alpine/Dockerfile 5.6/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:5.6-fpm-alpine

build-5.6-fpm-alpine:on-tags:
  stage: build
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:5.6-fpm-alpine-$CI_COMMIT_TAG -f 5.6/fpm-alpine/Dockerfile 5.6/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:5.6-fpm-alpine-$CI_COMMIT_TAG

build-7.1-apache:
  stage: build
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.1-apache -f 7.1/apache/Dockerfile 7.1/apache/
    - docker push $IMAGE_REPOSITORY:7.1-apache

build-7.1-apache:on-tags:
  stage: build
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:7.1-apache-$CI_COMMIT_TAG -f 7.1/apache/Dockerfile 7.1/apache/
    - docker push $IMAGE_REPOSITORY:7.1-apache-$CI_COMMIT_TAG

build-7.1-fpm-alpine:
  stage: build
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.1-fpm-alpine -f 7.1/fpm-alpine/Dockerfile 7.1/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:7.1-fpm-alpine

build-7.1-fpm-alpine:on-tags:
  stage: build
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:7.1-fpm-alpine-$CI_COMMIT_TAG -f 7.1/fpm-alpine/Dockerfile 7.1/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:7.1-fpm-alpine-$CI_COMMIT_TAG

build-7.2-apache:
  stage: build
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.2-apache -f 7.2/apache/Dockerfile 7.2/apache/
    - docker push $IMAGE_REPOSITORY:7.2-apache
    - docker tag $IMAGE_REPOSITORY:7.2-apache $IMAGE_REPOSITORY:latest
    - docker push $IMAGE_REPOSITORY:latest

build-7.2-apache:on-tags:
  stage: build
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:7.2-apache-$CI_COMMIT_TAG -f 7.2/apache/Dockerfile 7.2/apache/
    - docker push $IMAGE_REPOSITORY:7.2-apache-$CI_COMMIT_TAG

build-7.2-fpm-alpine:
  stage: build
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.2-fpm-alpine -f 7.2/fpm-alpine/Dockerfile 7.2/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:7.2-fpm-alpine

build-7.2-fpm-alpine:on-tags:
  stage: build
  only:
    - tags
  script:
    - docker build -t $IMAGE_REPOSITORY:7.2-fpm-alpine-$CI_COMMIT_TAG -f 7.2/fpm-alpine/Dockerfile 7.2/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:7.2-fpm-alpine-$CI_COMMIT_TAG

build:on-schedules:
  stage: build
  only:
    - schedules
  variables:
    MIN_VERSION: 0.1.1
  script:
    - apk update && apk add git
    - function version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }
    - docker build -t ${IMAGE_REPOSITORY}:5.6-apache -f 5.6/apache/Dockerfile 5.6/apache/
    - docker push $IMAGE_REPOSITORY:5.6-apache
    - docker build -t $IMAGE_REPOSITORY:5.6-fpm-alpine -f 5.6/fpm-alpine/Dockerfile 5.6/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:5.6-fpm-alpine
    - docker build -t $IMAGE_REPOSITORY:7.1-apache -f 7.1/apache/Dockerfile 7.1/apache/
    - docker push $IMAGE_REPOSITORY:7.1-apache
    - docker build -t $IMAGE_REPOSITORY:7.1-fpm-alpine -f 7.1/fpm-alpine/Dockerfile 7.1/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:7.1-fpm-alpine
    - docker build -t $IMAGE_REPOSITORY:7.2-apache -f 7.2/apache/Dockerfile 7.2/apache/
    - docker push $IMAGE_REPOSITORY:7.2-apache
    - docker tag $IMAGE_REPOSITORY:7.2-apache $IMAGE_REPOSITORY:latest
    - docker push $IMAGE_REPOSITORY:latest
    - docker build -t $IMAGE_REPOSITORY:7.2-fpm-alpine -f 7.2/fpm-alpine/Dockerfile 7.2/fpm-alpine/
    - docker push $IMAGE_REPOSITORY:7.2-fpm-alpine
    - > 
      for git_tag in $(git tag); do
        if version_gt $git_tag '0.1.1'; then
          git checkout tags/$git_tag
          docker build -t $IMAGE_REPOSITORY:5.6-apache-$git_tag -f 5.6/apache/Dockerfile 5.6/apache/
          docker push $IMAGE_REPOSITORY:5.6-apache-$git_tag
          docker build -t $IMAGE_REPOSITORY:5.6-fpm-alpine-$git_tag -f 5.6/fpm-alpine/Dockerfile 5.6/fpm-alpine/
          docker push $IMAGE_REPOSITORY:5.6-fpm-alpine-$git_tag
          docker build -t $IMAGE_REPOSITORY:7.1-apache-$git_tag -f 7.1/apache/Dockerfile 7.1/apache/
          docker push $IMAGE_REPOSITORY:7.1-apache-$git_tag
          docker build -t $IMAGE_REPOSITORY:7.1-fpm-alpine-$git_tag -f 7.1/fpm-alpine/Dockerfile 7.1/fpm-alpine/
          docker push $IMAGE_REPOSITORY:7.1-fpm-alpine-$git_tag
          docker build -t $IMAGE_REPOSITORY:7.2-apache-$git_tag -f 7.2/apache/Dockerfile 7.2/apache/
          docker push $IMAGE_REPOSITORY:7.2-apache-$git_tag
          docker build -t $IMAGE_REPOSITORY:7.2-fpm-alpine-$git_tag -f 7.2/fpm-alpine/Dockerfile 7.2/fpm-alpine/
          docker push $IMAGE_REPOSITORY:7.2-fpm-alpine-$git_tag
        fi
      done

trigger-typo3-build:on-schedules:
  stage: trigger-typo3-build
  only:
    - schedules
  trigger: crinis-org/docker-images/typo3-docker

after_script:
  - docker logout
