image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  IMAGE_REPOSITORY: crinis/typo3-php

before_script:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD https://index.docker.io/v1/

stages:
  - build

build-7.2-apache:
  stage: build
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.2-apache -f 7.2/apache/Dockerfile 7.2/apache/
    - docker push $IMAGE_REPOSITORY:7.2-apache

build-7.3-apache:
  stage: build
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.3-apache -f 7.3/apache/Dockerfile 7.3/apache/
    - docker push $IMAGE_REPOSITORY:7.3-apache

build-7.4-apache:
  stage: build
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.4-apache -f 7.4/apache/Dockerfile 7.4/apache/
    - docker push $IMAGE_REPOSITORY:7.4-apache

build-8.1-apache:
  stage: build
  except:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:8.1-apache -f 8.1/apache/Dockerfile 8.1/apache/
    - docker push $IMAGE_REPOSITORY:8.1-apache
    - docker tag $IMAGE_REPOSITORY:8.1-apache $IMAGE_REPOSITORY:latest
    - docker push $IMAGE_REPOSITORY:latest

build:on-schedules:
  stage: build
  only:
    - schedules
  script:
    - docker build -t $IMAGE_REPOSITORY:7.2-apache -f 7.2/apache/Dockerfile 7.2/apache/
    - docker push $IMAGE_REPOSITORY:7.2-apache
    - docker build -t $IMAGE_REPOSITORY:7.3-apache -f 7.3/apache/Dockerfile 7.3/apache/
    - docker push $IMAGE_REPOSITORY:7.3-apache
    - docker build -t $IMAGE_REPOSITORY:7.4-apache -f 7.4/apache/Dockerfile 7.4/apache/
    - docker push $IMAGE_REPOSITORY:7.4-apache
    - docker build -t $IMAGE_REPOSITORY:8.1-apache -f 8.1/apache/Dockerfile 8.1/apache/
    - docker push $IMAGE_REPOSITORY:8.1-apache
    - docker tag $IMAGE_REPOSITORY:8.1-apache $IMAGE_REPOSITORY:latest
    - docker push $IMAGE_REPOSITORY:latest
after_script:
  - docker logout
