version: "3"
services:

  php:
    image: crinis/typo3-php:8.4-apache
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    volumes:
      - "./var/:/var/www/html/var/:Z"
      - "./public/:/var/www/html/public/:Z"
      - "./vendor/:/var/www/html/vendor/:Z"
      - "./config/:/var/www/html/config/:Z"
      - "./packages/:/var/www/html/packages/:Z"
    ports:
      - 8080:8080
    userns_mode: "keep-id"
  cron:
    image: crinis/typo3-php:8.4-apache
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    volumes:
      - "./var/:/var/www/html/var/:Z"
      - "./public/:/var/www/html/public/:Z"
      - "./vendor/:/var/www/html/vendor/:Z"
      - "./config/:/var/www/html/config/:Z"
      - "./packages/:/var/www/html/packages/:Z"
    userns_mode: "keep-id"
    entrypoint: ["supercronic"]
    # Path to the crontab file.
    command: ["/custom/crontab"]
    # When image is used as root you can use cron instead of supercronic and don't need to specify the cron file.
    # entrypoint: ["/usr/sbin/cron", "-f"]
