name: build-root-images
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0'

env:
  IMAGE_NAME: typo3-php

jobs:
  build:
    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        if: matrix.php != '8.2'
        with:
          context: ${{ matrix.php }}/apache
          file: ${{ matrix.php }}/apache/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.php }}-apache
      -
        name: Build and push latest
        uses: docker/build-push-action@v4
        if: matrix.php == '8.2'
        with:
          context: ${{ matrix.php }}/apache
          file: ${{ matrix.php }}/apache/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.php }}-apache, ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
